on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Update github-metrics.svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          user: auguwu
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: America/Phoenix
          config_twemoji: yes
          repositories: 250
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_sections: most-used
          plugin_languages_threshold: 3%
          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_playlist: https://open.spotify.com/embed/playlist/6iuNlpFcsNrn1ICunlvAAi?theme=0
